/// pch.h
// (c) 2026 maplefoxo AUTOGENERATED
// Purpose :
// Precompiled headers

#pragma once

// #define NOMINMAX
// #define WIN32_LEAN_AND_MEAN
// #include <windows.h>
// C RunTime Header Files
#include <cstdlib>
#include <cstdint>
#include <cstdint>
#include <cctype>
#include <cfloat>

// Cpp std headers
#include <utility>
using std::pair;
#include <execution>
#include <iosfwd>
#include <sstream>
#include <algorithm>
#include <exception>
#include <stdexcept>
#include <forward_list>
#include <list>
using std::list;
#include <vector>
using std::vector;
#include <array>
using std::array;
#include <string>
using std::string;
#ifdef _MSC_VER 
#include <__msvc_string_view.hpp>
#else
#include <string_view>
#endif
using std::string_view;
#include <memory>
using std::shared_ptr;
using std::make_shared;
using std::unique_ptr;
using std::make_unique;
using std::weak_ptr;

